/*
    module Decrypt()

    Takes ciphertext to be decrypted and two subkeys generated by another
    module to return the plaintext. This, in essence, is a mirror of the
    encrypt module but with the two Fk modules wired in opposite order;
    subKey2 is taken in as the first key and subKey1 is taken in the second
    Fk.
*/

module Decrypt(

    input [7:0] Ciphertext,
    input [7:0] subKey1,
    input [7:0] subKey2,
    output [7:0] Plaintext

);

wire [7:0] IP_out;

IP_Function m1(Ciphertext, IP_out);

wire [7:0] FK2_out;

FK_operation m2(IP_out, subKey2, FK2_out);

wire [7:0] SWAP_result;

SWAP m3(FK2_out, SWAP_result);

wire [7:0] FK1_out;

FK_operation m4(SWAP_result, subKey1, FK1_out);

IP_Inverse m5(FK1_out, Plaintext);

endmodule